name: Build and Release Typester

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        runtime: [linux-x64, osx-arm64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore typester.sln

      - name: Build Typester
        run: |
          dotnet publish typester.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -o typester-${{ matrix.runtime }}

      - name: Rename binary
        run: |
          mv typester-${{ matrix.runtime }}/typester typester-${{ matrix.runtime }}

      - name: Upload release binaries
      uses: softprops/action-gh-release@v1
        with:
          files: typester-${{ matrix.runtime }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

